spring:
  profiles:
    active: dev
---
spring:
  application:
    name: springcloud-provider-dept
server:
  port: 8201
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
spring:
  application:
    name: springcloud-provider-dept
server:
  port: 8202
spring:
  config:
    activate:
      on-profile: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
