spring:
  profiles:
    active: dev
---
spring:
  application:
    name: springcloud-provider-dept
  config:
    activate:
      on-profile: dev
server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
spring:
  application:
    name: springcloud-provider-dept
  config:
    activate:
      on-profile: test
server:
  port: 8202

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
