spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  application:
    name: springcloud-config-provider-dept
  config:
    activate:
      on-profile: dev
  #  configuration:
  #    map-underscore-to-camel-case: true #驼峰命名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.dawn.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka 描述信息

# 开启info信息
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
# info 配置
info:
  app: dawn.Chuang-springcloud
  company: dawn.Chuang company
  phone: 111111
  website: rushbi.me

---
server:
  port: 8002
spring:
  application:
    name: springcloud-config-provider-dept
  config:
    activate:
      on-profile: test
  #  configuration:
  #    map-underscore-to-camel-case: true #驼峰命名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.dawn.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka 描述信息

# 开启info信息
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
# info 配置
info:
  app: dawn.Chuang-springcloud
  company: dawn.Chuang company
  phone: 111111
  website: rushbi.me